# Generated by Django 6.0.2 on 2026-02-27 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_userprofile_and_ticket_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='interested_users',
        ),
        migrations.RemoveField(
            model_name='event',
            name='organiser',
        ),
    ]
