# Generated by Django 6.0.2 on 2026-02-28 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_booking'),
        ('events', '0004_add_event_relationships'),
    ]

    operations = [
    ]
